{% set version = "1.0.2" %}

package:
  name: mpifft4py
  version: {{ version }}

source:
  url: https://github.com/spectralDNS/mpiFFT4py/archive/mpiFFT4py-{{ version }}.tar.gz
  sha256: 5d2bc067123b3b4d068bc85bccd693aa7287600d8c34c079ea1ca069342f9b58

build:
  number: 5
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - mpi4py
    - pyfftw

test:
  requires:
    - pytest
  imports:
    - mpiFFT4py

about:
  home: https://github.com/spectralDNS/mpiFFT4py
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'Parallel FFT in 3D or 2D using MPI for Python. Slab or pencil decomposition possible in 3D.'
  description: |
    mpiFFT4py performs FFTs in parallel in Python. It is developed to be able
    to do FFTs in parallel on a three-dimensional computational box
    (a structured grid), but there are also routines for doing the FFTs on a
    2D mesh. It implements both the slab and the pencil decompositions.

extra:
  recipe-maintainers:
    - mikaem
