{% set name = "mpiFFT4py" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spectralDNS/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 2b67ed6fa6c98aa9591ac51afb6a815c3a401b85a4d5d9070e20865d27162fba

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - toolchain
    - python
    - cython

  host:
    - numpy 1.12.*

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - mpi4py
    - cython
    - pyfftw

test:
  source_files:
    - tests

  requires:
    - pytest

  imports:
    - mpiFFT4py

about:
  home: https://github.com/spectralDNS/mpiFFT4py
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'Parallel FFT in 3D or 2D using MPI for Python. Slab or pencil decomposition possible in 3D.'
  description: |
    mpiFFT4py performs FFTs in parallel in Python. It is developed to be able
    to do FFTs in parallel on a three-dimensional computational box
    (a structured grid), but there are also routines for doing the FFTs on a
    2D mesh. It implements both the slab and the pencil decompositions.

extra:
  recipe-maintainers:
    - mikaem
