{% set name = "mpiFFT4py" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spectralDNS/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 09fa43762dd6d818bf9936c966f09954476d93d4a43b92dd39f2ae29dcea6c2c

build:
  skip: true  # [win]
  number: 3

requirements:
  build:
    - toolchain
    - python
    - cython
    - numpy x.x

  run:
    - python
    - numpy x.x
    - scipy
    - mpi4py
    - cython
    - pyfftw

test:
  source_files:
    - tests

  requires:
    - pytest

  imports:
    - mpiFFT4py

about:
  home: https://github.com/spectralDNS/mpiFFT4py
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'Parallel FFT in 3D or 2D using MPI for Python. Slab or pencil decomposition possible in 3D.'
  description: |
    mpiFFT4py performs FFTs in parallel in Python. It is developed to be able
    to do FFTs in parallel on a three-dimensional computational box
    (a structured grid), but there are also routines for doing the FFTs on a
    2D mesh. It implements both the slab and the pencil decompositions.

extra:
  recipe-maintainers:
    - mikaem
