# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VGQDGVAGdmeC0ZvJ3sh8K0UsAWHeUg+E5jvb8nJN/6qjw4wa090CytTB2YpuI8rFQMCjqAXRGDFjmWkeSUFAKwYR9DucnWjUBQ73P2DN4ZAHLI+6QNCQCLspamHiMEnFH+59fQF5LoWWkxYPow+b4WT5O+KUFkXvdfuvLvizMQA1QdgTNlbFLO0jwIToauqTH/35SJi7tin0WlpkPYdhJOQWalnn618a2GIJ6Z7fUIgJfNtAujfjvXQ3wf4bQYuuOI3Wx/dcTxzlikGFFyHtADmTxI4o2YNszstQiXuz3+TgAUwfq+JUyNQv2+1+riazD2vIbwtFyB6+MC4uJqdxk1Zx1sTD4no5o9CJ7aMjDfe4V362nEaZoea3sCmq9WXuc+7nAwjyvJbiFUDUB7zwDo40yhVZGdcmQ88Xcty6ZhGptwI8BB7XA9KMFDGoKVi8zdH0EGB5zWYxabFrFDoWjcwnZOzsmcgo8fCsjxc9Y++3Jo39m345m7atjUh4xRWwOu38bLJFg+LdJ45m+O38sJbtj4/GkSBOFadCNQ/XLhWwUtWCXhK/jsB+pWROG4lmc1MwjKUIDEe+Co9uwiTp19yzj84qBUMorQs7imhj3CAOefQXFs4fpa5oAyV2Ck/+66KcNZbifMzBG9Q8cJM9lyG1UKBeOK9/aGvVXyvA7RY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
