travis:
  secure:
    BINSTAR_TOKEN: VGQDGVAGdmeC0ZvJ3sh8K0UsAWHeUg+E5jvb8nJN/6qjw4wa090CytTB2YpuI8rFQMCjqAXRGDFjmWkeSUFAKwYR9DucnWjUBQ73P2DN4ZAHLI+6QNCQCLspamHiMEnFH+59fQF5LoWWkxYPow+b4WT5O+KUFkXvdfuvLvizMQA1QdgTNlbFLO0jwIToauqTH/35SJi7tin0WlpkPYdhJOQWalnn618a2GIJ6Z7fUIgJfNtAujfjvXQ3wf4bQYuuOI3Wx/dcTxzlikGFFyHtADmTxI4o2YNszstQiXuz3+TgAUwfq+JUyNQv2+1+riazD2vIbwtFyB6+MC4uJqdxk1Zx1sTD4no5o9CJ7aMjDfe4V362nEaZoea3sCmq9WXuc+7nAwjyvJbiFUDUB7zwDo40yhVZGdcmQ88Xcty6ZhGptwI8BB7XA9KMFDGoKVi8zdH0EGB5zWYxabFrFDoWjcwnZOzsmcgo8fCsjxc9Y++3Jo39m345m7atjUh4xRWwOu38bLJFg+LdJ45m+O38sJbtj4/GkSBOFadCNQ/XLhWwUtWCXhK/jsB+pWROG4lmc1MwjKUIDEe+Co9uwiTp19yzj84qBUMorQs7imhj3CAOefQXFs4fpa5oAyV2Ck/+66KcNZbifMzBG9Q8cJM9lyG1UKBeOK9/aGvVXyvA7RY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
