travis:
  secure:
    BINSTAR_TOKEN: Pp8FwGunOhw8X4F7KafosLQ2Zu3mNp+PJMDloWfspT9uRXQfc1iJLeCyXSvsIPfGWxTOuqwDUag3mzsafA3hiRhYUKoeRgiZd5bSmz1m+7QcH4SVI03Ca7mDaImlMlEe19utCnPxSt+0MQWWBz2dtXWW9qPBs4aCazMQCQXLIHUxYBFp8w5Xt6SyldEZV77m2GXV1eimKybg81WscpHhRQpfaXemQE19y2O38k8YxeCtEgwmYGUVnAKnDBtlEJKLM6tKgyZtdh8pVH1+heOofjST7pBzyxEzi4KK5GcQa4AQsKTmX/sElcNsXAYQsfK2XOD9zonruvIs89Cl73iubv3VleL9ADv2uYxQ+6Vp97nauUAY9kQUBAmGevxV/EsfaVrs5szeI1GoHdWbBM6TaKlPsXsXD43YzxXhne9Rt733qbvTJWEb9agVe50x153ZpqdMgdjHeUnXFntfFLOWU62zsWp7rG1Wo1tjtV7y0CebIvyUgSW72VCXiQWzfaG+4HBe1qbnHMulw8zjJH+9m7kpWAL7I5+JsAI1yImdtwXh7kBWluIzzpH4jU5gY1IMKwzfRUi6u5DXCMj2Itlg4h/Ep0DZfKq8YRcqEkZo+o7sXbnD7jaiTKx6iNNCG8CKDLj2BGo7ea+X7gP/CcW3vCuy5dLTANT+sUG0QP44iMg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
