travis:
  secure:
    BINSTAR_TOKEN: erf0I2dn1WO7lJaJrB6FSuB0WBagHDBGIIdm5NfAhADuemcu64eanN/npJ/n+LFnBFkemIdZ09mRxYvXLIdJwd5hhqqNWyppgw2Pu2WYHB+2PlvvoZedWt0vxuNJGnEkG+/ApXgFaF1QKmZFulDGCQf2nutWqKoTYY8sTb+c/4JbhwWA16XEnQBmS5ifo8pOP51OvQbRgINU8R9DZlGSmdrDUqly7t4LBqlvff8rCrxeC5AklrZdE8R5mMTdtOlrL2WHdshOQLnRdMDyv98lJzUzH7xayzIxZGSprN1Ob496Gncb5P4h+72HGMCJQlNSHYSBPYvohYKSmKKY5FPa4Q4kUgz7mFX48iGmTcJjwXhWCWnHQOew2lDLGlYbN9Lbuqf9CMStIhZ0xS+u+vfMontd4BDvKCJM2fqIsiaB2tcVr7Mi4Zxr8tpEQIT8RSRUqiAWwKW2bTE28Jc/YOpAgytFIIV89DI8qd5stRAwXG98+qNGIp9BDhrEFIIK4HhO8OAXjXiPOFV/kUibKFPTek+x1r6W+c2fZrJD6bG4h6po81hXxFaqs+w3MYKkr4ah4hDoQ6jj9HrBikUHbz3rE64FZ6JxmUsARmUZILNloIYjBO5wbP4J4+lbMGroSDkCDZCeFixNIkuqil3w127iejzDgUMIOan4+ouH1Hne7tM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
